// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCpxL_7BALXGqB890RTJtXPpALMWtDFS4',
    appId: '1:436089005733:web:2ff48ba4b17b58e1c30f4c',
    messagingSenderId: '436089005733',
    projectId: 'goldenbelt-942ae',
    authDomain: 'goldenbelt-942ae.firebaseapp.com',
    storageBucket: 'goldenbelt-942ae.appspot.com',
    measurementId: 'G-DK3XR1M0P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrHy7OzZPajcOd-Rmz-F49PGiUE8PUhps',
    appId: '1:436089005733:android:597855e2d7163375c30f4c',
    messagingSenderId: '436089005733',
    projectId: 'goldenbelt-942ae',
    storageBucket: 'goldenbelt-942ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcA_FOUtYmwK6urJPpyqWykwWNXr4HmLU',
    appId: '1:436089005733:ios:4218ea44415e6c08c30f4c',
    messagingSenderId: '436089005733',
    projectId: 'goldenbelt-942ae',
    storageBucket: 'goldenbelt-942ae.appspot.com',
    iosBundleId: 'com.app.goldenbelt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcA_FOUtYmwK6urJPpyqWykwWNXr4HmLU',
    appId: '1:436089005733:ios:57c23bd97ba6b56ac30f4c',
    messagingSenderId: '436089005733',
    projectId: 'goldenbelt-942ae',
    storageBucket: 'goldenbelt-942ae.appspot.com',
    iosBundleId: 'com.example.goldenbelt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIvZHT5Ep_oK50Ux50pnISZAObg1CutLY',
    appId: '1:436089005733:web:f3f48dd1c399440ac30f4c',
    messagingSenderId: '436089005733',
    projectId: 'goldenbelt-942ae',
    authDomain: 'goldenbelt-942ae.firebaseapp.com',
    storageBucket: 'goldenbelt-942ae.appspot.com',
    measurementId: 'G-HJNSCS97KL',
  );

}